### ISSUE TITLE
[BUG] - 3v5

### ISSUE THREAD

**Issue by PencilMario** [TouchMe-Inc/l4d2_mix_team#11]
![image](https://user-images.githubusercontent.com/72117241/236457648-6ffe742b-0344-4c5c-9b1c-ac67359627f8.png)
Perhaps it is because someone joined in the middle of the mix while mt_capitan was running.

**Comment by TouchMe-Inc** [comment]
If it's the latest version, then:
Yes, this is possible, since there is a delay between team changes for connected players (see [Event_PlayerTeam](https://github.com/TouchMe-Inc/l4d2_mix_team/blob/main/addons/sourcemod/scripting/mix_team.sp#L542))

I don't have enough data for this case, including what's in event.team and event.newteam. Try decreasing the timer from 1 second to 0.1
